### EDA on the transformed time series

In [1]:
# Packages
import pandas as pd

In [21]:
# Load the data
df = pd.read_csv('../data/final_datasets/time_series/transformed_time_series/coffee_time_series.csv', 
                 index_col = 'DATE', 
                 parse_dates = True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1092 entries, 2021-01-04 to 2023-12-31
Data columns (total 28 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   daily_average_quantity                          1092 non-null   float64
 1   daily_total_quantity                            1092 non-null   float64
 2   daily_dispersion_quantity                       1092 non-null   float64
 3   daily_average_price                             1092 non-null   float64
 4   daily_dispersion_price                          1092 non-null   float64
 5   daily_total_sales                               1092 non-null   float64
 6   daily_dispersion_total_sales                    1092 non-null   float64
 7   daily_difference_average_quantity               1092 non-null   float64
 8   daily_difference_total_quantity                 1092 non-null   float64
 9   daily_difference_dispersion_quantity            1092 non-null   float64
 10  daily_difference_average_price                  1092 non-null   float64
 11  daily_difference_dispersion_price               1092 non-null   float64
 12  daily_difference_total_sales                    1092 non-null   float64
 13  daily_difference_dispersion_total_sales         1092 non-null   float64
 14  daily_second_difference_average_quantity        1092 non-null   float64
 15  daily_second_difference_total_quantity          1092 non-null   float64
 16  daily_second_difference_dispersion_quantity     1092 non-null   float64
 17  daily_second_difference_average_price           1092 non-null   float64
 18  daily_second_difference_dispersion_price        1092 non-null   float64
 19  daily_second_difference_total_sales             1092 non-null   float64
 20  daily_second_difference_dispersion_total_sales  1092 non-null   float64
 21  daily_percentage_change_average_price           1092 non-null   float64
 22  daily_percentage_change_total_quantity          1092 non-null   float64
 23  elasticity                                      1092 non-null   float64
 24  difference_elasticity                           1092 non-null   float64
 25  second_difference_elasticity                    1092 non-null   float64
 26  cumulative_total_sales                          1092 non-null   float64
 27  cumulative_total_quantity                       1092 non-null   float64
dtypes: float64(28)
memory usage: 247.4 KB

In [28]:
df.columns.tolist()

['daily_average_quantity',
 'daily_total_quantity',
 'daily_dispersion_quantity',
 'daily_average_price',
 'daily_dispersion_price',
 'daily_total_sales',
 'daily_dispersion_total_sales',
 'daily_difference_average_quantity',
 'daily_difference_total_quantity',
 'daily_difference_dispersion_quantity',
 'daily_difference_average_price',
 'daily_difference_dispersion_price',
 'daily_difference_total_sales',
 'daily_difference_dispersion_total_sales',
 'daily_second_difference_average_quantity',
 'daily_second_difference_total_quantity',
 'daily_second_difference_dispersion_quantity',
 'daily_second_difference_average_price',
 'daily_second_difference_dispersion_price',
 'daily_second_difference_total_sales',
 'daily_second_difference_dispersion_total_sales',
 'daily_percentage_change_average_price',
 'daily_percentage_change_total_quantity',
 'elasticity',
 'difference_elasticity',
 'second_difference_elasticity',
 'cumulative_total_sales',
 'cumulative_total_quantity']

In [39]:
list_of_subgroups = []
with open('../data/final_datasets/time_series/reformated_subgroup_names.txt', 'r') as file:
    for line in file:
        list_of_subgroups.append(line[:-1])
    
for n, sub in enumerate(list_of_subgroups):
    # Load the data
    df = pd.read_csv('../data/final_datasets/time_series/' + sub + '_time_series.csv', 
                     index_col = 'DATE', 
                     parse_dates = True)
    print(n, sub, df['QUANTITY'].isnull().sum())

0 chips 0
1 coffee 0
2 nuts 0
3 cookies 0
4 baking 0
5 outerwear 0
6 underwear 0
7 tops 0
8 infants 0
9 canned_goods 0
10 boys 0
11 shirts 0
12 bottoms 0
13 pasta 0
14 juice 0
15 headphones 0
16 history 0
17 soda 0
18 utensils 0
19 lips 0
20 romance 0
21 eyes 0
22 board_games 0
23 reference 0
24 face 0
25 styling 0
26 wearables 0
27 smartphones 0
28 bedroom 0
29 biography 0
30 science_fiction 0
31 textbooks 0
32 specialty 0
33 treatments 0
34 speakers 0
35 pants 0
36 desktops 0
37 girls 0
38 dresses 0
39 pots_and_pans 0
40 bakeware 0
41 mystery 0
42 arts_and_crafts 0
43 card_games 0
44 cleansers 0
45 shampoo 0
46 camping 0
47 jackets 0
48 equipment 0
49 self_help 0
50 dining 0
51 major_appliances 0
52 vehicles 0
53 figures 0
54 home_audio 0
55 tablets 0
56 accessories 0
57 laptops 0
58 living_room 0
59 stem 0
60 children_learning 0
61 small_appliances 0
62 water_sports 0
63 moisturizers 0
64 supplements 0
65 hiking 0
66 treatment 0
67 baseball 0
68 apparel 0
69 learning 0
70 soccer 0
71 puzzles 0
72 playsets 0

In [46]:
list_of_subgroups = []
with open('../data/final_datasets/time_series/reformated_subgroup_names.txt', 'r') as file:
    for line in file:
        list_of_subgroups.append(line[:-1])
    
for n, sub in enumerate(list_of_subgroups):
    print(n, sub)
    # Load the data
    df = pd.read_csv('../data/final_datasets/time_series/' + sub + '_time_series.csv', 
                     index_col = 'DATE', 
                     parse_dates = True)

    # IQR method to detect outliers
    df = df.select_dtypes(include = ['number']).drop(columns = ['TRANSACTION_ID'])
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    Q3
    IQR = Q3 - Q1
    IQR
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    for col in df.columns:
        print(col, df[col].loc[(df[col] < lower_bound[col]) | (df[col] > upper_bound[col])].shape[0]/df.shape[0]*100.0)
    
    print("============================\n")

0 chips
QUANTITY 3.6053936432062215
PRICE 0.45749652195626583
TOTAL_SALES 11.578675132879107
============================

1 coffee
QUANTITY 4.416343845852577
PRICE 0.6749184707793845
TOTAL_SALES 8.59459522341527
============================

2 nuts
QUANTITY 3.5559423743796135
PRICE 0.2899194105815717
TOTAL_SALES 15.258444949385797
============================

3 cookies
QUANTITY 3.54482364051742
PRICE 0.7153521507588493
TOTAL_SALES 21.206047282602306
============================

4 baking
QUANTITY 4.354001252154214
PRICE 0.1915840193265357
TOTAL_SALES 8.549824012601185
============================

5 outerwear
QUANTITY 23.536695314835608
PRICE 0.07038457283155489
TOTAL_SALES 19.784420763213586
============================

6 underwear
QUANTITY 24.546551749310154
PRICE 2.415308471342849
TOTAL_SALES 23.510446221305134
============================

7 tops
QUANTITY 23.8858743307509
PRICE 0.4477134633834346
TOTAL_SALES 19.22253628645409
============================

8 infants
QUANTITY 23.793729560202618
PRICE 0.5877892521484355
TOTAL_SALES 21.329347680308675
============================

9 canned_goods
QUANTITY 4.391604463742418
PRICE 0.15997004347550753
TOTAL_SALES 8.435735270228225
============================

10 boys
QUANTITY 23.8133260551439
PRICE 0.27554528350096397
TOTAL_SALES 17.908701307751272
============================

11 shirts
QUANTITY 3.7333171006376404
PRICE 0.5788985101428984
TOTAL_SALES 15.188324633622985
============================

12 bottoms
QUANTITY 23.863885568497363
PRICE 0.7057762457645703
TOTAL_SALES 21.340696880685208
============================

13 pasta
QUANTITY 4.364834517772858
PRICE 0.3429602322733409
TOTAL_SALES 8.28491695351088
============================

14 juice
QUANTITY 4.669466666246562
PRICE 0.002835708501769167
TOTAL_SALES 8.313982248464779
============================

15 headphones
QUANTITY 4.083704683087671
PRICE 0.36857483309664885
TOTAL_SALES 15.729559440445293
============================

16 history
QUANTITY 4.289887065728015
PRICE 1.2444306847397397
TOTAL_SALES 8.922009395485322
============================

17 soda
QUANTITY 4.635938640288446
PRICE 0.3768145263264377
TOTAL_SALES 8.476339805053577
============================

18 utensils
QUANTITY 4.619639981364432
PRICE 0.377480309761296
TOTAL_SALES 8.665172397348467
============================

19 lips
QUANTITY 5.579773642703032
PRICE 0.04197256319816205
TOTAL_SALES 8.845165423444254
============================

20 romance
QUANTITY 3.9189259048645932
PRICE 0.5682867207751445
TOTAL_SALES 9.688199280687114
============================

21 eyes
QUANTITY 5.5447561206778
PRICE 0.0750798187677246
TOTAL_SALES 9.31287098536687
============================

22 board_games
QUANTITY 3.9835328449764758
PRICE 1.172130903460187
TOTAL_SALES 15.341924245131318
============================

23 reference
QUANTITY 3.844091227338408
PRICE 1.4025234995307543
TOTAL_SALES 11.820152244186566
============================

24 face
QUANTITY 5.371097401383436
PRICE 0.23630585156103945
TOTAL_SALES 7.862404187698635
============================

25 styling
QUANTITY 24.918695050855632
PRICE 0.5769542393512186
TOTAL_SALES 19.130687106900464
============================

26 wearables
QUANTITY 24.069155115000388
PRICE 1.4373112367381708
TOTAL_SALES 20.32525362038256
============================

27 smartphones
QUANTITY 24.115649430378763
PRICE 1.1683840785813089
TOTAL_SALES 20.979624189863383
============================

28 bedroom
QUANTITY 5.854217646335611
PRICE 1.910423846785356
TOTAL_SALES 8.26515112456027
============================

29 biography
QUANTITY 4.2145822161314035
PRICE 2.34840811138255
TOTAL_SALES 7.234701781564679
============================

30 science_fiction
QUANTITY 3.870062241573863
PRICE 1.2233001192199269
TOTAL_SALES 9.076264867602085
============================

31 textbooks
QUANTITY 3.953895301237699
PRICE 5.326441173165524
TOTAL_SALES 8.28945467387989
============================

32 specialty
QUANTITY 4.013976375572778
PRICE 2.4156399995163884
TOTAL_SALES 11.065436681134715
============================

33 treatments
QUANTITY 3.983038262906925
PRICE 0.8274621743362978
TOTAL_SALES 16.857376210668733
============================

34 speakers
QUANTITY 4.208034087031782
PRICE 0.8272097068149098
TOTAL_SALES 14.340520792590064
============================

35 pants
QUANTITY 3.6770103436770105
PRICE 0.11636636636636637
TOTAL_SALES 17.321905238571905
============================

36 desktops
QUANTITY 24.973169804859918
PRICE 1.6473948611302507
TOTAL_SALES 20.760515974927863
============================

37 girls
QUANTITY 24.212084094529008
PRICE 0.24915658822693315
TOTAL_SALES 18.993591324668593
============================

38 dresses
QUANTITY 24.06972789829669
PRICE 0.4958372343954019
TOTAL_SALES 19.485017822430653
============================

39 pots_and_pans
QUANTITY 4.72890781127813
PRICE 2.7430706403684075
TOTAL_SALES 8.094100269354417
============================

40 bakeware
QUANTITY 4.8109134712611334
PRICE 3.2691174789635196
TOTAL_SALES 8.386455759643368
============================

41 mystery
QUANTITY 3.915546855322289
PRICE 1.7918454461496314
TOTAL_SALES 9.439114815093038
============================

42 arts_and_crafts
QUANTITY 3.9077045837396933
PRICE 3.6829506161893786
TOTAL_SALES 9.18742796347194
============================

43 card_games
QUANTITY 3.9245437952132525
PRICE 0.5721247606849431
TOTAL_SALES 16.415339369948722
============================

44 cleansers
QUANTITY 4.081780024371531
PRICE 2.1622963397571873
TOTAL_SALES 13.222457913977523
============================

45 shampoo
QUANTITY 3.720228005225496
PRICE 0.10080326186698489
TOTAL_SALES 17.670857008538896
============================

46 camping
QUANTITY 4.01360975698157
PRICE 0.8993131693880141
TOTAL_SALES 13.876153023685688
============================

47 jackets
QUANTITY 24.927314321129433
PRICE 0.015038416318048834
TOTAL_SALES 18.137697208323083
============================

48 equipment
QUANTITY 24.89524391411597
PRICE 0.8740692780835222
TOTAL_SALES 21.43407547909666
============================

49 self_help
QUANTITY 4.321520758449328
PRICE 0.01785154271102212
TOTAL_SALES 7.928497334330446
============================

50 dining
QUANTITY 6.030616530609289
PRICE 0.4074479948634518
TOTAL_SALES 9.743993280004634
============================

51 major_appliances
QUANTITY 3.9346065638980696
PRICE 0.5873426673018087
TOTAL_SALES 8.720270688359713
============================

52 vehicles
QUANTITY 3.85084792472515
PRICE 1.9989960728732985
TOTAL_SALES 9.953642188561137
============================

53 figures
QUANTITY 4.1491375943603765
PRICE 0.3875758219919618
TOTAL_SALES 11.611949595368865
============================

54 home_audio
QUANTITY 4.258058675304166
PRICE 1.810152748927438
TOTAL_SALES 16.34720329136971
============================

55 tablets
QUANTITY 4.108083352415846
PRICE 1.7225148207515966
TOTAL_SALES 15.138793476324963
============================

56 accessories
QUANTITY 24.516831642670155
PRICE 0.17434964005235604
TOTAL_SALES 19.828309064136125
============================

57 laptops
QUANTITY 3.9299132910839383
PRICE 1.1163708695048802
TOTAL_SALES 19.326785191124543
============================

58 living_room
QUANTITY 5.900988814341863
PRICE 0.7222831933999752
TOTAL_SALES 8.480339948856294
============================

59 stem
QUANTITY 3.9338768015750993
PRICE 0.8472795248155564
TOTAL_SALES 8.699547601402546
============================

60 children_learning
QUANTITY 3.9852905341042515
PRICE 1.3895350125163377
TOTAL_SALES 8.364901087702975
============================

61 small_appliances
QUANTITY 3.9795493067326126
PRICE 0.9630720497929923
TOTAL_SALES 9.687960210064187
============================

62 water_sports
QUANTITY 4.012877939529675
PRICE 3.042553191489362
TOTAL_SALES 15.522956326987684
============================

63 moisturizers
QUANTITY 4.182417939369501
PRICE 2.263142861943245
TOTAL_SALES 8.766388324176594
============================

64 supplements
QUANTITY 3.750147015171966
PRICE 0.011201155959294998
TOTAL_SALES 19.06324732712416
============================

65 hiking
QUANTITY 4.2711234911792015
PRICE 0.16487999774907852
TOTAL_SALES 12.227005430348049
============================

66 treatment
QUANTITY 3.915275994865212
PRICE 1.6868229624124498
TOTAL_SALES 13.55933157669527
============================

67 baseball
QUANTITY 3.873118485440611
PRICE 1.8892574176582215
TOTAL_SALES 19.102053687571445
============================

68 apparel
QUANTITY 3.8300152275675368
PRICE 0.6976481867914951
TOTAL_SALES 19.8849472674976
============================

69 learning
QUANTITY 4.016922594797869
PRICE 3.020369790034472
TOTAL_SALES 8.734565966781572
============================

70 soccer
QUANTITY 3.8784142232418093
PRICE 2.9073442866546317
TOTAL_SALES 22.12736005839454
============================

71 puzzles
QUANTITY 3.8691304156844373
PRICE 0.23646719475233172
TOTAL_SALES 8.509158528193039
============================

72 playsets
QUANTITY 4.2776166622726075
PRICE 2.844421009461874
TOTAL_SALES 8.495913524914316
============================